### ISSUE TITLE
rubberband option in baseline not working with Python 3 kernel

### ISSUE THREAD

**Issue by charlesll** [charlesll/rampy#1]
There is a problem with ConvexHull line 201...

**Comment by sjfraser05** [comment]
If this issue still open, may I try and contribute to fix this? Thank you for your consideration

**Comment by charlesll** [comment]
Please feel free to submit a pull request to fix this bug !

**Comment by charlesll** [comment]
Commit #28 should have fixed this issue. Will be added to next version of Rampy

**Comment by charlesll** [comment]
Included in v0.4.8, closing.
