### ISSUE TITLE
Raman maps from Renishaw spectrometer

### ISSUE THREAD

**Issue by KacperGrodecki** [charlesll/rampy#20]
I think it is valuable to add new functionality- possibility to read and analyse Raman maps taken from spectrometers like Renishaw or Horiba. I have already done it on Ammon1/spectroscopy repo. Part of it is reading of (quite havy Renishaw type of files) and change it to Horiba-like (much more elegant). Next step is to make possibility to analize peak params and save it as maps of params-very usefull in Raman spectroscopy in solid state physics. 
My code is based on pandas and numpy. It is not very elegant because it is quite old but I may update and upgrade it.

**Comment by charlesll** [comment]
It's a good idea, indeed. It's something I always wanted to do, but I am not doing enough mapping to justify spending a lot of time on coding this...

Do you think you could become a contributor and add your piece of code via a pull request to rampy to do so ?

This could be added to 0.4.7 for instance, giving us some time for testing. I have Horiba spectrometers, and if you have a Renishaw one, we can cover a broad range of cases.

The map analysis could further benefit from the ML features that should also be expanded in the future.

**Comment by KacperGrodecki** [comment]
Yes, I would like to become a contributor of this project and add code via pull request. I need some time to do it- update, upgrade and merge with Your code.

**Comment by charlesll** [comment]
Perfect!

I guess the best practice will be to create a fork of rampy, create a new
branch from the 0.4.6 dev branch, and work on this new branch then do a
pull request to include your modifications. Don't hesitate to let me know
if you need anything!

Le jeu. 4 févr. 2021 à 13:32, Kacper Grodecki <notifications@github.com> a
écrit :

**Comment by charlesll** [comment]
Solved in 0.4.6
