### ISSUE TITLE
read_horiba function may return bad raman shifts (as string)

### ISSUE THREAD

**Issue by charlesll** [charlesll/rampy#25]
We need to change in the function:

`lambdas=df.columns.values[2:]`

to 

`lambdas=df.columns.values[2:].values`

For now, a quick fix is to add the line

`my_map.w = my_map.w.astype(float)`

after generating your map object.

**Comment by KacperGrodecki** [comment]
You mean you wont to change lambdas from string to float right? I think it needs casting on float in this line:
lambdas=df.columns.values[2:]
As I remember pandas is on numpy and thus while generating .values we generate numpy- maybe of strings. Isn't it easier to perform:
lambdas=float(df.columns.values[2:]) 
However I'm not sure it it will generate array or not.

**Comment by charlesll** [comment]
I will have a look, but maybe the safest option is

`lambdas = df.columns.values[2:].values.astype(float)`

**Comment by charlesll** [comment]
Corrected in v0.4.8, closing.
