### ISSUE TITLE
Re

### ISSUE THREAD

**Issue by KacperGrodecki** [charlesll/rampy#27]
Re

**Comment by charlesll** [comment]
???

**Comment by KacperGrodecki** [comment]
I'm very sory, I did not even notticed that what has happend-how to delete it?

**Comment by KacperGrodecki** [comment]
Nothing to comment

**Comment by KacperGrodecki** [comment]
Hi one again.
For 90%it was my son. Sorry for that- it will never repeat.

Regards
Kacper

śr., 19 maj 2021 o 15:19 Charles Le Losq ***@***.***>
napisał(a):
