### ISSUE TITLE
ModuleNotFoundError: No module named 'rampy'

### ISSUE THREAD

**Issue by serkovic** [charlesll/rampy#31]
Hello, I am trying to import the rampy package but I get an error. I am launching it from Google Collaborator. It worked fine last year.

!pip install rampy
import rampy

Requirement already satisfied: rampy in /usr/local/lib/python3.10/dist-packages (0.5.1)
Requirement already satisfied: numpy>=1.12 in /usr/local/lib/python3.10/dist-packages (from rampy) (1.23.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from rampy) (1.11.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from rampy) (1.2.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from rampy) (1.5.3)
Requirement already satisfied: xlrd in /usr/local/lib/python3.10/dist-packages (from rampy) (2.0.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from rampy) (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->rampy) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->rampy) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->rampy) (4.47.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->rampy) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->rampy) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->rampy) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->rampy) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->rampy) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->rampy) (2023.3.post1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->rampy) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->rampy) (3.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib->rampy) (1.16.0)
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-22-088cf61cc5e1>](https://localhost:8080/#) in <cell line: 3>()
      1 get_ipython().system('pip install rampy')
      2 
----> 3 import rampy

ModuleNotFoundError: No module named 'rampy'

If I use:
!apt install rampy
import rampy

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package rampy
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-23-982cbe109f1d>](https://localhost:8080/#) in <cell line: 3>()
      1 get_ipython().system('apt install rampy')
      2 
----> 3 import rampy

ModuleNotFoundError: No module named 'rampy'

Does anyone know how to fix this or what is wrong?

Thanks!
Laura

**Comment by charlesll** [comment]
Hi, 

It apparently is not an error on your side. It is an error with the way I packaged the 0.5.1 release. I will work to fix it asap. Please try installing v0.5.0 in the meantime. This should be resolved in a few hours, I hope...

**Comment by charlesll** [comment]
@serkovic OK the problem appears to be solved. It initiated from a different directory structure when using pyproject.toml, which made void the package structure in v0.5.1.

Please upgrade directly to 0.5.2 that has been just released, via

`pip install rampy --upgrade`

This should upgrade to the new version and you should be good to go!

Please let me know if this works!

Thanks for letting me know about this installation problem, that is actually critical to have people telling me if things work or no!

Cheers,
Charles

**Comment by serkovic** [comment]
It works!
Thanks a lot!!!!
Cheers,
Laura

**Comment by charlesll** [comment]
OK cool, closing this issue then! Thanks again for taking the time to raise this issue!
