### ISSUE TITLE
[Suggestion] Applying the neighbour parameter to the averaging function

### ISSUE THREAD

**Issue by kevihiiin** [charlesll/rampy#32]
**Description of the suggestion**
In the current state, the `neigh` parameter in the [despiking function](https://charlesll.github.io/rampy/html/rampy.html#rampy.spectranization.despiking) is only used to define the numbers of points around the spikes to calculate the replacement value for the spike.

**Use case/Problem**
The despiking function does not work as intended on our dataset, as the spikes seem to be broader than the default window size for the smoothing function. 

**Suggestion**
A more flexible approach would be to allow the user to specify the window size for the smoothing function.
My suggestion would be to pass the `neigh` parameter to the smoothing function.

I will provide a PR in a due course.

**Comment by charlesll** [comment]
Merged and integrated in the new release. Closing this, thanks for the help!
